---
title: "Final Project"
author: "Christopher Loan & Merly Klaas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(rmdHelpers)
```

```{r cache = T}
## names aren't as intuitive as in the example DA gave in class 
## I put the links in a tibble
## you can map through the links and then let the user specify which years

links <- 
  c(GY_2020 = 
      'https://download.gosa.ga.gov/2020/Graduation_Rate_2020_Dec112020.csv', 
    GY_2019 = 
      'https://download.gosa.ga.gov/2019/Graduation_Rate_2019_Dec2nd_2019.csv', 
    GY_2018 = 
      'https://download.gosa.ga.gov/2018/Graduation_Rate_2018_JAN_24th_2019.csv',
    GY_2017 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2017_DEC_1st_2017.csv', 
    GY_2016 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2016_DEC_1st_2016.csv',
    GY_2015 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2015_DEC_1st_2016.csv', 
    GY_2014 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2014_DEC_1st_2016.csv',
    GY_2013 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2013_DEC_1st_2016.csv',
    GY_2012 = 
      'https://gosa.georgia.gov/sites/gosa.georgia.gov/files/related_files/site_page/Graduation_Rate_2012_4yr.csv',
    GY_2011 = 
    'https://download.gosa.ga.gov/2011/Graduation_Rate_2011_MAR_23_2020.csv'
    )
## Merly: Improve function to be able to specify by year

download_clean_data <- function(number_of_years = 10, start, end) {
  download_links <- links[1:number_of_years]
  map_dfr(download_links, ~rio::import(.x, setclass = "tibble")) %>% 
    janitor::clean_names() %>% 
    mutate(
      student_group = 
        factor(gsub('Grad Rate -', '', label_lvl_1_desc)), 
      num_graduates = program_total, 
      perc_graduate = program_percent,
      prop_graduate = program_percent/100,
      num_students = num_graduates/prop_graduate,
      granularity = detail_lvl_desc,
      grad_year = as.numeric(
        str_replace(long_school_year, '1[:digit:]-', '')
      )
      ) %>% 
    filter(
      ## only want schools (not districts or whole state)
      granularity == 'School' &  grad_year >= start & grad_year <= end &
      ## eliminate schools which couldn't have graduation 
      ## (i.e., non high schools)
      grepl(pattern = '12' , x = grades_served_desc) == T
    ) %>% 
    select(
      instn_name, 
      grad_year,
      student_group, 
      num_students, 
      num_graduates, 
      perc_graduate, 
      grades_served_desc,
      )
}

d0 <- 
  download_clean_data(start=2011, end=2016) #Example for between 2011 - 2017

rio::export(
  d0,
  here::here(
    'Data', 
    paste0('Cleaned_Data_', Sys.Date(), '.csv')
    ), 
  format = ','
  )
```

## write function to choose student groups (here is some code to start)

```{r}
## Merly: turn into function

## possible groups the user can subset
## write an if statement in the function
## that outputs these possible groups in a warning
## if they specify a group that isn't in here
# 
# stu_group_options <-
#   
#   gsub( 
#     pattern = 'Grad Rate -', 
#     replacement = '',
#     x = unique(d0$student_group)
#     )
# warning(
#   'Specified group (or groups) not available. There are ',
#   length(stu_group_options), 
#   ' groups available for subsetting: ',
#   knitr::combine_words(stu_group_options),
#   '. Please select one or more of these groups.'
# )
# 
# ## example of selected groups
# 
# groups <- 
#   c(
#     'ALL Students', 
#     'Economically Disadvantaged', 
#     'Black',
#     'White',
#     'Not Economically Disadvantaged',
#     'Students With Disability', 
#     'Students Without Disability'
#   )
# 
# schools_of_interest <- c('Appling County High School')
# 
# dat <- 
#   d0 %>% 
#   filter(
#     ## only looking at certain student groups to make data manageable
#     student_group %in% groups & 
#       instn_name %in% schools_of_interest
#     ) 
```
```{r}
stu_group_options <- 
  gsub( 
    pattern = 'Grad Rate -', 
    replacement = '',
    x = unique(d0$student_group)
    )

## example of selected groups
groups <- 
  c(
    'ALL Students', 
    'Economically Disadvantaged', 
    'Black',
    'White',
    'Not Economically Disadvantaged',
    'Students With Disability', 
    'Students Without Disability',
    'English Language Learner'
  )

schools_of_interest <- c('Appling County High School')


select_group <- function (test_group){
  check_group <- groups %in% stu_group_options
if (any(check_group == F)){
  NA_group <- groups[which (check_group == F)]
length_NA <- length(NA_group)
print_NA_group <- printList(toPrint = NA_group, finalSepWord = "and", midSep = ",")
warning(
  length_NA , ' specified group (or groups) not available: ' , print_NA_group,  '. There are ',
  length(stu_group_options), 
  ' groups available for subsetting: ',
  knitr::combine_words(stu_group_options),
  '. Please select one or more of these groups.'
)}
}
select_group(test_group = groups)



dat <- 
  d0 %>% 
  filter(
    ## only looking at certain student groups to make data manageable
    student_group %in% groups & 
      instn_name %in% schools_of_interest
    ) 
```

## map through selected schools and make the plots

We can make this function print schools by name, too. So the default will be all schools, but they can specify some schools if they want.

```{r}
## Merly: Figure out how to map through these and save for all schools
## (after Chris): turn into function
dat %>% 
  mutate(
    student_group = 
      trimws(
        gsub(
          pattern = 'Students', replacement = '', student_group)),
    student_group = str_to_sentence(student_group),
    student_group = 
      gsub(
        pattern = ' ', replacement = '\n', student_group
        )
    ) %>% 
  drop_na(student_group, perc_graduate) %>%
  group_by(instn_name, student_group) %>% 
  mutate(
    average_grad = mean(perc_graduate),
    se_grad = sd(perc_graduate)/sqrt(n()),
    lower_ci_90 =
      average_grad - 1.65*se_grad,
    upper_ci_90 =
      average_grad + 1.65*se_grad,
    lower_ci_95 =
      average_grad - 1.96*se_grad,
    upper_ci_95 =
      average_grad + 1.96*se_grad,
    lower_ci_99 =
      average_grad - 2.58*se_grad,
    upper_ci_99 =
      average_grad + 2.58*se_grad,
    ) %>%
  ungroup() %>% 
  ggplot(
    aes(
      y = 
        fct_reorder(
          student_group, 
          average_grad
          ),
      x = average_grad, 
      color = student_group)
    ) +
  geom_vline(
    aes(
      xintercept = mean(average_grad)
      )
    ) +
  geom_errorbar(
    aes(
      xmin = lower_ci_90, 
      xmax = upper_ci_90
    ),
    width = 0.2, 
    alpha = 0.1
  ) +
  geom_errorbar(
    aes(
      xmin = lower_ci_95, 
      xmax = upper_ci_95
    ),
    width = 0.4, 
    alpha = 0.2
  ) +
  geom_errorbar(
    aes(
      xmin = lower_ci_99, 
      xmax = upper_ci_99
    ),
    width = 0.6, 
    alpha = 0.6
  ) +
  geom_point() +
  theme_minimal() + 
  theme(
    axis.text.y = 
      element_text(
        vjust = 0, 
        size = 7
        ), 
    legend.position = 'none',
    plot.title.position = 'plot'
  ) +
  colorblindr::scale_fill_OkabeIto() + 
  colorblindr::scale_color_OkabeIto() +
  labs(
    y =  NULL,
    x = 'Percent Graduation', 
    caption = 'Horizontal line = average percent graduation of all groups
source = https://gosa.georgia.gov/dashboards-data-report-card/downloadable-data
Error bars represent 90%, 95%, & 99% CIs', 
title = paste0('Percent Graduation of Student Groups for
{SCHOOL NAME} from ', min(dat$grad_year), ' to ', max(dat$grad_year)))
```

## write a function to save the plots

```{r}

```

I'll make it shiny